### PR TITLE
flashy: Refactor logger interface and restart syslog appropriately

### PR DESCRIPTION
**Pull request by lhl2617**
Summary: 
As title. Make logger interface easier to work with, and restart (and reacquire syslog) immediately after killing data partition processes.

Test Plan:
Unit tests `go test ./...`

Flash tests TBD.

### CODE REVIEW

**Comment by doranand** [comment]
Hi @lhl2617 just saw this one.

**Comment by lhl2617** [comment]
Hey @doranand  no worries - also realised that this might be dangerous because there is a very short interval between "killing" `syslog` and starting it up, and for every retry it starts it... not sure if this would be good for flaky systems. Nevertheless this makes syslog only dead during the crucial `fuser` cmd.

**Comment by lhl2617** [comment]
@doranand  @kawmarco are we seeing any syslog errors which could benefit from this? this would make logging more reliable :D

**Comment by williamspatrick** [comment]
I think this was contributed via phabricator already?

**Pull request closed without merging**
