### PR TITLE
Extended Application handler to support IPMI Cold and Warm reset comm…

### PR DESCRIPTION
**Pull request by sivabmc**
Extended Application handler to support IPMI Cold and Warm reset commands, intital support is included further changes will be done to comply with IPMI spec once relevant entities are available

### CODE REVIEW

**Comment by sivabmc** [comment]
Extended Application handler to support IPMI Cold and Warm reset commands, intital support is included further changes will be done to comply with IPMI spec once relevant entities are available

**Comment by theopolis** [comment]
@tfanggi, @jmetha, what do you guys think?

**Comment by jmehta** [comment]
Merge to helium: 31bd8ffa7e5ec1d25d53231e04df866222454f47

**Comment by sivabmc** [comment]
jmehta, Thanks for merge my changes !

**Pull request closed without merging**
