### PR TITLE
Fix a typo in a comment

### PR DESCRIPTION
**Pull request by PeterMartini**

### CODE REVIEW

**Comment by theopolis** [comment]
Thanks @PeterMartini, I'm going to use this a test-case to try some of the new internal commit syncing (Github => Facebook internal => Github using out release bots). Please forgive me if this takes a few days to show up in master.

**Comment by PeterMartini** [comment]
No worries; I'm using this as a test case too :smile:  I'd like to get more involved and this seemed like a nice way to (re)test the waters.  Happy to do what it takes to shake out any process issues there may be.

**Comment by PeterMartini** [comment]
Hi @theopolis, any updates?

**Comment by jmehta** [comment]
Merged c20a7680099e21717fda7e67d29514c4167a8c11 to origin/master.
Resolved.

**Pull request closed without merging**
