### PR TITLE
flashy: s/fbnd/northdome

### PR DESCRIPTION
**Pull request by lhl2617**
# Happy New Year!

## Summary 

- As per https://github.com/facebook/openbmc/commit/ba0c790c69c71a63d26c0ea8182a45dbc664fa10 
- Intern tests will fail if the source-of-truth file used is updated and flashy's files aren't.

## Additional Information
- we could migrate the intern test to run off `tools/platforms/platform_build_names` (unless there are intern `build_name`s that cannot be released, which shouldn't be the case)--I unfortunately do not have access to the intern test code (but will again in 6-7 months!). I can however make an extern test and the intern test (iirc in `tools/flashy/tests/facebook`) can therefore be deleted. Sound good?
- https://github.com/facebook/openbmc/commit/81a9aef5a834440aab76b217257cb47c5bca760b added an empty string to the end of `tools/platforms/platform_build_names`

## Test plan
#m eyes 
#m flashy
#m testhard

### CODE REVIEW

**Comment by doranand** [comment]
Hi @lhl2617, Happy New Year! Will merge.

**Review by williamspatrick — APPROVED** [review]
Awesome, thanks!  I just hadn't gotten around to moving / renaming the file yet.

**Comment by lhl2617** [comment]
Hey @doranand and @williamspatrick -- miss the team! just making sure that you've seen the two points under Additional Information

**Comment by doranand** [comment]
> Hey @doranand and @williamspatrick -- miss the team! just making sure that you've seen the two points under Additional Information

@lhl2617  I raised a diff to correct the empty string.  Which intern test trigger are you talking about?  It's not clear to me at all.  Probably better to DM if internal.  Thanks!

**Pull request closed without merging**
