### PR TITLE
DO_NOT_MERGE: u-boot/kernel: fix PV for kirkstone+ distros

### PR DESCRIPTION
**Pull request by williamspatrick**
Signed-off-by: Patrick Williams <patrick@stwcx.xyz>

### CODE REVIEW

**Comment by peterdelevoryas** [comment]
I think you'll still need to update the `PREFERRED_VERSION_linux-aspeed` and `PREFERRED_VERSION_u-boot` for each kirkstone+ machine to have a wildcard for the git revision.

Edit: Actually, it might have to be updated for dunfell and rocko machines too, since the PV has been updated in all the recipes.

**Comment by williamspatrick** [comment]
> I think you'll still need to update the `PREFERRED_VERSION_linux-aspeed` and `PREFERRED_VERSION_u-boot` for each kirkstone+ machine to have a wildcard for the git revision.
> 
> Edit: Actually, it might have to be updated for dunfell and rocko machines too, since the PV has been updated in all the recipes.

Isn't that already covered?

```
meta-fby35/conf/machine/fby35.conf:PREFERRED_VERSION_linux-aspeed = "5.15.%"
meta-fby35/meta-halfdome/conf/machine/halfdome.conf:PREFERRED_VERSION_linux-aspeed = "5.15.%"
```

A test recipe parsing in halfdome gave me:
```
PV="5.15.27+gitAUTOINC+6e91671551"
```

**Comment by peterdelevoryas** [comment]
> > I think you'll still need to update the `PREFERRED_VERSION_linux-aspeed` and `PREFERRED_VERSION_u-boot` for each kirkstone+ machine to have a wildcard for the git revision.
> > Edit: Actually, it might have to be updated for dunfell and rocko machines too, since the PV has been updated in all the recipes.
> 
> Isn't that already covered?
> 
> ```
> meta-fby35/conf/machine/fby35.conf:PREFERRED_VERSION_linux-aspeed = "5.15.%"
> meta-fby35/meta-halfdome/conf/machine/halfdome.conf:PREFERRED_VERSION_linux-aspeed = "5.15.%"
> ```
> 
> A test recipe parsing in halfdome gave me:
> 
> ```
> PV="5.15.27+gitAUTOINC+6e91671551"
> ```

Yeah some platforms already have the wildcard, but like fby3, for example, does not. And since this affects parsing for some reason, you had to change _all_ the kernel recipes, but that means you also have to change all the machine configs I think.

**Comment by peterdelevoryas** [comment]
Looks good to me, yeah I'm like 99% sure this will work now. And, it probably doesn't actually require any ship-it mirroring changes, since the wildcard changes can be included on the main configs.

I guess this change wasn't as hard to do as I thought lolz.

**Pull request closed without merging**
