### PR TITLE
flashy: Add extra check for data partition mount state in galaxy100

### PR DESCRIPTION
**Pull request by lhl2617**
Summary:
The unmount data partition remediation may fall back to remounting RO. In that case formatting it on galaxy100 devices with Diag folders will cause the device to reboot.

Make sure the data partition is unmounted before proceeding.

Test plan:
Unit tests `go test ./...`

Flash tests TODO

### CODE REVIEW

**Comment by doranand** [comment]
Hey @lhl2617.  Thanks a lot for the diff!  There are two other improvements needed here which I'll make because I need them ASAP.

1. There is a chicken-and-egg type problem.  In order to fix corruption on /mnt/data we need to unmount it.  However in order to unmount /mnt/data we first copy the contents off, which fails because of the corruption.  I think a compromise solution would be to limit the copy to /mnt/data/etc/ssh only, which is all we really need to keep around for the duration of the upgrade.

2. Remount to R/O should also be accompanied by fuser -km in a loop.

**Comment by doranand** [comment]
Actually, I see remountRODataPartition() already does killDataPartitionProcesses(), and there's no point retrying there (it gets called if retrying doesn't work).

**Comment by doranand** [comment]
I limited the copy to /mnt/data/etc/ssh only.

The change passes all internal tests, including on a galaxy100 that had jffs2 issues and was previously stuck.

Currently landing.

**Comment by lhl2617** [comment]
Thanks!

There was conversation before why we didn't only copy etc/ssh, I can't really remember. If I'm not mistaken it should just be that it would be difficult to track for any new things we put inside images that rely on the data partition. But for upgrades I think it is safe to assume only ssh is required.

**Pull request closed without merging**
